steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-f ./Pokemon Center/pom.xml']
    dir: 'pokemon-center'

  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: [ 'tests' ]