package com.pokemon.center.util;

import com.pokemon.center.utilities.response.KeyResponseInterface;

public enum PokemonCenterResponse implements KeyResponseInterface {
    SUCCESSFUL_TRANSACTION("SUCCESSFUL_TRANSACTION"),
    NO_RESULT_FOUND_BY_ID("NO_RESULT_FOUND_BY_ID"),
    INVALID_IDENTIFICATION("INVALID_IDENTIFICATION"),
    INVALID_PERSON_CREATION_PARAMS("INVALID_PERSON_CREATION_PARAMS"),
    ROLE_NOT_FOUND("ROLE_NOT_FOUND"),
    IDENTIFICATION_ALREADY_USED("IDENTIFICATION_ALREADY_USED"),
    INVALID_SYMPTOM_CREATION_PARAMS("INVALID_SYMPTOM_CREATION_PARAMS"),
    SYMPTOM_NOT_FOUND("SYMPTOM_NOT_FOUND"),
    INVALID_TREATMENT_CREATION_PARAMS("INVALID_TREATMENT_CREATION_PARAMS"),
    TREATMENT_NOT_FOUND("TREATMENT_NOT_FOUND"),
    INVALID_POKEMON_CREATION_PARAMS("INVALID_POKEMON_CREATION_PARAMS"),
    POKEMON_NOT_FOUND_IN_EXTERNAL_API("POKEMON_NOT_FOUND_IN_EXTERNAL_API"),
    POKEMON_ALREADY_EXISTS("POKEMON_ALREADY_EXISTS"),
    MEDICAL_RECORD_SYMPTOM_NOT_FOUND("MEDICAL_RECORD_SYMPTOM_NOT_FOUND"),
    INVALID_MEDICAL_RECORD_TREATMENT_CREATION_PARAMS("INVALID_MEDICAL_RECORD_TREATMENT_CREATION_PARAMS"),
    MEDICAL_RECORD_TREATMENT_NOT_FOUND("MEDICAL_RECORD_TREATMENT_NOT_FOUND"),
    POKEMON_SPECIES_NOT_FOUND("POKEMON_SPECIES_NOT_FOUND"),
    NO_RESULT_FOUND_BY_NICKNAME("NO_RESULT_FOUND_BY_NICKNAME"),
    POKEMON_NICKNAME_ALREADY_EXISTS("POKEMON_NICKNAME_ALREADY_EXISTS"),
    INVALID_POKEMON_PERSON_CREATION_PARAMS("INVALID_POKEMON_PERSON_CREATION_PARAMS"),
    PERSON_NOT_EXISTS("PERSON_NOT_EXISTS"),
    POKEMON_NOT_EXISTS("POKEMON_NOT_EXISTS"),
    POKEMON_PERSON_NOT_FOUND("POKEMON_PERSON_NOT_FOUND"),
    MEDICAL_RECORD_NOT_FOUND("MEDICAL_RECORD_NOT_FOUND");
    public final String key;

    PokemonCenterResponse(String key) {
        this.key = key;
    }

    @Override
    public String getValue() {
        return key;
    }

}
